name: Deckventures
favicon: null
layout_spectrum: 0.487941135186702
typography_spectrum: 0.20402468973770738
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.010956461075693369
  lightness: 0.25242071808315814
  saturation: 0.3072315289173275
  rhythmicContrast: 0.9098297299351543
purpose: []
